apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: ga9a5dwvj-python 
  janus-idp.io/tekton: ga9a5dwvj-python
  backstage.io/kubernetes-id: ga9a5dwvj-python
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: ga9a5dwvj-python
resources: 
- application-dev.yaml 
- application-stage.yaml 
- application-prod.yaml  