apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    tad.gitops.set/image: ".spec.template.spec.containers[0].image"
    tad.gitops.get/image: ".spec.template.spec.containers[0].image"
    tad.gitops.set/replicas: ".spec.replicas"
    tad.gitops.get/replicas: ".spec.replicas"
  name: ga9a5dwvj-python
spec:
  replicas: 1
  template:
    spec:
      containers:
        - image: quay.io/rhtap_qe/rhtap-qe:84e9c7719079926e66e4682e118c501314d2ef4d@sha256:2908f03c160944fad2eb2b5dbda6643c755b87f82ef1f52204846dbcfabcec25
          name: container-image
