apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: ga9a5dwvj-python
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: ga9a5dwvj-python 
  name: ga9a5dwvj-python
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: ga9a5dwvj-python 
